### PR TITLE
chore(package.json): add commonjs support

### PR DESCRIPTION
**Pull request by bendrucker**

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@bendrucker - This looks great.

**Comment by bendrucker** [comment]
:tada:

**Comment by ThomasBurleson** [comment]
@bendrucker - tried to use our merge process (which gives you formal credit). Had issues. I did a manual merge and said "Thanks @bendrucker" in the commit... this was easier than asking you to rebase your PR.

**Comment by bendrucker** [comment]
No problem

**Comment by ThomasBurleson** [comment]
@bendrucker - Question: 
Since Angular Material depends upon angular-animate and angular-aria, does it make sense to do this in the `index.js`:

```js
// Insure these are loaded
require('angular-animate');
require('angular-aria');

require('./angular-material');

module.exports = 'ngMaterial';
```

**Comment by bendrucker** [comment]
This could cause issues if someone isn't fully using npm for their apps. So if you're dropping in `angular` in a concatenated file or from a CDN, you can't `require` it. That said, browserify makes it easy for you to just ignore that require and return an empty object. So I'd say go for it.

**Pull request closed without merging**
