### PR TITLE
Remove all functions and variables that are not required

### PR DESCRIPTION
**Pull request by MartinMuzatko**
Everything that is not required for the material standalone grid to work should be removed.
Including unused Functions and everything that does not belong to breakpoints or gutter

### CODE REVIEW

**Comment by gkalpak** [comment]
This should be opened in https://github.com/angular/material.

**Comment by MartinMuzatko** [comment]
@gkalpak angular/material does no longer support the standalone version of the flexgrid, see this issue: https://github.com/angular/material/issues/7660#issuecomment-199440833

> The standalone flexgrid [was part of angular](https://github.com/angular/material/issues/7660#issuecomment-199440833), but was migrated to [bower-material](https://github.com/angular/bower-material/), which contains a [standalone build](https://github.com/angular/material/blob/master/src/core/style/layout.scss). The grid is not actively maintained unfortunately. Hence it contains lots of variables and functions not required for the grid.
source: https://github.com/MartinMuzatko/flexproperties

**Comment by ThomasBurleson** [comment]
Will not merge. See existing  [angular-material.layout-attributes.css](https://github.com/angular/bower-material/blob/master/modules/layouts/angular-material.layout-attributes.css)

**Comment by MartinMuzatko** [comment]
So, there will be no cleanup of the variables and functions that enables other contributors and devs to have a better overview of the source code to adapt the source sass to their needs?

**Comment by ThomasBurleson** [comment]
@MartinMuzatko - We will not merge your changes into this repository as `angular/bower-material` is a build deployment repository. Instead we should fix the issue in `angular/material`. I will use your PR changes to shape the fix in the build scripts. Thank you!

**Pull request closed without merging**
